from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('help/', views.help, name='help'),
	path('subforums/new/', views.subforums_new, name='subforums_new'),
	path('subforums/create/', views.subforums_create, name='subforums_create'),
	path('subforums/<int:subforum_id>/', views.subforums_detail, name='subforums_detail'),
	path('subforums/<int:subforum_id>/like/', views.subforums_like, name='subforums_like'),
	path('subforums/<int:pk>/update/', views.SubforumUpdate.as_view(), name='subforums_update'),
	path('subforums/<int:subforum_id>/add_post/', views.add_post, name='add_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/update/', views.update_post, name='update_post'),
	path('subforums/<int:subforum_id>/post/<int:pk>/delete/', views.PostDelete.as_view(), name='delete_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/comment/<int:pk>/delete_comment/', views.CommentDelete.as_view(), name='delete_comment'),
	path('company/', views.CompanyList.as_view(), name='company_index'),
	path('company/<int:pk>/', views.CompanyDetail.as_view(), name='company_detail'),
	path('company/create/', views.CompanyCreate.as_view(), name='company_create'),
	path('company/<int:company_id>/subforums/new/', views.company_subforums_new, name='company_subforums_new'),
	path('company/<int:company_id>/subforums/create/', views.company_subforums_create, name='company_subforums_create'),
	path('company/<int:company_id>/subforums/<int:pk>/update/', views.Company_SubforumUpdate.as_view(), name='company_subforums_update'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/', views.company_subforums_detail, name='company_subforums_detail'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/like/', views.company_subforums_like, name='company_subforums_like'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/add_post/', views.add_company_post, name='add_company_post'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/add_comment/', views.add_company_comment, name='add_company_comment'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/comment/<int:pk>/delete/', views.Company_CommentDelete.as_view(), name='delete_company_comment'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:company_post_id>/update/', views.update_company_post, name='update_company_post'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:pk>/delete/', views.Company_PostDelete.as_view(), name='delete_company_post'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/<int:user_id>/application/new/', views.applications_new, name='applications_new'),
    path('profile/<int:user_id>/application/create/', views.applications_create, name='applications_create'),
    path('profile/<int:user_id>/application/<int:application_id>/', views.applications_detail, name='applications_detail'),
    path('profile/<int:user_id>/application/<int:pk>/delete/', views.Job_ApplicationDelete.as_view(), name='applications_delete'),
    path('profile/<int:user_id>/application/<int:pk>/update/', views.Job_ApplicationUpdate.as_view(), name='applications_update'),
    path('profile/<int:user_id>/application/<int:application_id>/status_update/', views.status_update, name='status_update'),
    path('profile/<int:user_id>/application/<int:application_id>/add_component/', views.add_component, name='add_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:pk>/delete/', views.Application_ComponentDelete.as_view(), name='delete_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/add_note/', views.add_note, name='add_note'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/note/<int:pk>/delete/', views.Component_NoteDelete.as_view(), name='delete_note'),
    path('profile/<int:user_id>/liked/', views.liked, name='liked'),
  	path('accounts/signup/', views.signup, name='signup'), 
	path('faq/', views.faq, name='faq')
]