# Generated by Django 4.2.5 on 2023-09-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=600)),
                ('date', models.DateField(auto_now_add=True)),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subforum')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
