# Generated by Django 4.2.5 on 2023-09-20 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_photo_company_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subforum_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subforum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
