# Generated by Django 4.2.5 on 2023-09-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='descriptions', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default='industry', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='photo_url',
            field=models.CharField(default='company photo url', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(default='url to company', max_length=150),
            preserve_default=False,
        ),
    ]
