# Generated by Django 4.2.5 on 2023-09-20 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_company_subforum_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name='Date:')),
                ('contact', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('salary', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date Applied')),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('will_apply', 'Will Apply'), ('heard_back', 'Heard Back'), ('interview', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], default='applied', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job_application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application_component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='application_component',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job_application'),
        ),
        migrations.AddField(
            model_name='application_component',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
