# Generated by Django 4.2.5 on 2023-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_application_component_job_application_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_component',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
