# Generated by Django 4.2.5 on 2023-09-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('url', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=150)),
            ],
        ),
    ]
