# Generated by Django 4.2.5 on 2023-09-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_application_component_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(max_length=150, verbose_name='Company Job Postings URL'),
        ),
    ]
