# Generated by Django 4.2.5 on 2023-09-18 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_company_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='company_subforum',
            name='content',
            field=models.TextField(default='defaulted content string for the existing subforums so that the column isnt blank', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subforum',
            name='content',
            field=models.TextField(default='defaulted content string for the existing subforums so that the column isnt blank', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_photo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.company_subforum'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subforum'),
        ),
    ]
