# Generated by Django 4.2.5 on 2023-09-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_post_company_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
